name: Auto-clean workflow runs
on:
  watch:
    types: [started]
jobs:
  cleanup:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 5
